MODEL:
  TYPE: cloformer
  NAME: cloformer_global
  cloformer:
    in_chans: 3
    num_classes: 1000
    embed_dims: [32, 64, 128, 256]
    depths: [2, 2, 6, 2]
    num_heads: [4, 4, 8, 16]
    group_splits: [[4], [4], [8], [16]]
    kernel_sizes: [[], [], [], []]
    window_sizes: [8, 4, 2, 1]
    mlp_kernel_sizes: [5, 5, 5, 5]
    mlp_ratios: [4, 4, 4, 4]
    attn_drop: 0.
    mlp_drop: 0.
    qkv_bias: True
    drop_path_rate: 0.
    use_checkpoint: False
    
DATA:
  NUM_WORKERS: 10
  BATCH_SIZE: 256
  DATA_PATH: /home/fanqh/imagenet
  DATASET: imagenet